name: tamales
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  decimal:  ^0.3.0
  flutter:
    sdk: flutter


 
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/icon/1.png"



flutter:

  
  uses-material-design: true

  
  assets:
      - assets/images/
